services:
  backend:
    build:
      context: ./backend/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - ./backend:/workspace/backend
    entrypoint: /bin/bash
    command: -i -c "while :; do sleep 10; done"
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - dev-network

  frontend:
    build:
      context: ./frontend/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/workspace/frontend
    entrypoint: /bin/bash
    command: -i -c "while :; do sleep 10; done"
    ports:
      - "4200:4200"
    env_file:
      - .env
    networks:
      - dev-network

  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  postgres_data:
