services:
  backend:
    build:
      context: ./backend/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - ./backend:/workspace/backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - dev-network

  frontend:
    build:
      context: ./frontend/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/workspace/frontend
    ports:
      - "4200:4200"
    networks:
      - dev-network

  postgres:
    image: postgres:15-alpine
    # env_file:
    #   - .env
    environment:
      # POSTGRES_USER: ${DATASOURCE_USER}
      # POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      # POSTGRES_DB: ${DATASOURCE_DB}
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
